version: "3.8"
services:
  postgres_it:
    image: postgres:13
    environment:
      POSTGRES_USER: tenantuser
      POSTGRES_PASSWORD: tenantpass
      POSTGRES_DB: tax_enforce_it
    ports:
      - "5433:5432"
    volumes:
      - postgres_it_data:/var/lib/postgresql/data

  postgres_de:
    image: postgres:13
    environment:
      POSTGRES_USER: tenantuser
      POSTGRES_PASSWORD: tenantpass
      POSTGRES_DB: tax_enforce_de
    ports:
      - "5434:5432"
    volumes:
      - postgres_de_data:/var/lib/postgresql/data

volumes:
  postgres_it_data:
  postgres_de_data:
